server:
  port: 8003

spring:
  application:
    name: short-link-aggregation
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

aggregation:
  remote-url: http://127.0.0.1:${server.port}

short-link:
  group:
    max-num: 20
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20
  domain:
    default: heng.yiyunblog.cn
    scheme: https
  demo-mode:
    enable: false
    blacklist:
      - /api/short-link/admin/v1/group
      - /api/short-link/admin/v1/recycle-bin/remove
      - /api/short-link/admin/v1/recycle-bin/remove/batch
      - /api/short-link/admin/v1/create
      - /api/short-link/admin/v1/create/batch
      - /api/short-link/admin/v1/update
      - /api/short-link/admin/v1/user
      - /api/short-link/admin/v1/user/logout
      - /api/short-link/admin/v1/recycle-bin/save
      - /api/short-link/admin/v1/recycle-bin/save/batch
  stats:
    locale:
      amap-key: 8795a2aa4c9c55b6db78fda7bf1bb1ea
  goto-domain:
    white-list:
      enable: false
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
